name: Shuttle Deploy

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: shuttle-hq/deploy-action@main
        with:
          deploy-key: ${{ secrets.SHUTTLE_API_KEY }}
          secrets: |
            OAUTH_CLIENT_ID = '${{ secrets.OAUTH_CLIENT_ID }}'
            OAUTH_CLIENT_SECRET = '${{ secrets.OAUTH_CLIENT_SECRET }}'
            JWT_SECRET = '${{ secrets.JWT_SECRET }}'
            REDIS_URL = '${{ secrets.REDIS_URL }}'
